package CIF::Client::Plugin::Bindzone;

sub type { return 'output'; }

my $default_output = '/etc/namedb/cif_blockeddomain.hosts';

sub write_out {
    my $self = shift;
    my $config = shift;
    my $feed = shift;
    my @array = @{$feed->{'feed'}->{'entry'}};
    $config = $config->{'config'};

    if($config->{'bindzone_path'}){
        $default_output = $config->{'bindzone_path'};
    }

    my $text = '// generated by: '.$0." at ".time()."\n";
    foreach (@array){
        $text .= 'zone "'.$_->{'address'}.'" {type master; file "'.$default_output.'";};'."\n";
    }
    return $text;
}
1;
