#!/usr/bin/perl -w

use warnings;
use strict;

use CIF::Message::Infrastructure;
use CIF::Message;
use Data::Dumper;

my $bucket = CIF::Message::Infrastructure->new();
my @recs = $bucket->retrieve_from_sql(qq{
    severity < 'high' AND severity IS NOT NULL
    AND impact != 'infrastructure whitelist' AND impact != 'search'
    ORDER BY id DESC
    LIMIT 500000
});

foreach my $rec (@recs){
    # could have been deleted by rdata ->delete()
    next if(ref($rec) eq 'Class::DBI::Object::Has::Been::Deleted');
    if($bucket->isWhitelisted($rec->address())){
        my $address = $rec->address();
        print 'removing: '.$address.' -- whitelisted'."\n";
        my $msg = CIF::Message->retrieve(uuid => $rec->uuid());
        $msg->delete();
    }
}
