#!/usr/bin/perl -w

use warnings;
use strict;

use CIF::Message::Domain;
use CIF::Message::DomainSimple;
use DateTime;
use Net::DNS::Resolver;

my $now = DateTime->from_epoch(epoch => time());
$now = $now->ymd().'T'.$now->hms().'Z';

my $b = CIF::Message::Domain->new();

my @recs = $b->retrieve_from_sql(qq{
    ttl IS NULL
    AND severity = 'high'
    ORDER BY id DESC
    LIMIT 2000 
});

warn $#recs;
my $x = 0;
foreach my $rec (@recs){
    my $id = CIF::Message::DomainSimple->insert({
        relatedid   => $rec->id(),
        source      => $rec->source(),
        impact      => substr($rec->impact(), 0, 10),
        description => substr($rec->description(), 0, 10),
        address     => $rec->address(),
        confidence  => $rec->confidence(),
        nsres       => Net::DNS::Resolver->new(nameservers => ['8.8.8.8','8.8.8.4'],debug => 1),
        restriction => $rec->restriction(),
        alternativeid   => $rec->alternativeid(),
        alternativeid_restriction => $rec->alternativeid_restriction(),
        detecttime  => $rec->detecttime(),
        severity    => $rec->severity(),
    });
    print $id."\n";
    warn $x++;
}

warn $#recs;
